import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nextjs Amazona",
  description: "Generated by create next app",
};

export default async function HomeLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className= 'flex flex-col min-h-screen'>
      <Header />
      <main className="flex-1 flex flex-col ">{children}</main>
      <Footer />
    </div>

    
      
  )
}
